---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
  tasks:
  - include_role: 
      name: utils_hosts_vmware
    when: infra == 'vmware'
  - include_role:
      name: utils_hosts_aws
    when: infra == 'aws'

- name: Fortinet FortiGate setup roles
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  tasks:
  - include_role: 
      name: fortigate_setup_wmware
    when: infra == 'vmware'
  - include_role: 
      name: fortigate_setup_aws
    when: infra == 'aws'
    
- name: Fortinet FortiGate roles
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"  
  roles:
    # - fortigate_change_password # no permissions via API
    - fortigate_config_network
    - fortigate_create_rules
    - fortigate_connect_fortianalyzer
    - fortigate_gather_facts

