---

- name: Fortinet FortiAnalyzer roles
  hosts: fortianalyzer
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortianalyzer_gather_facts
    - fortianalyzer_device_authorization
    - fortianalyzer_config_settings
