---

- name: Get FortiGate name from repo
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Get FortiGate node
    set_fact:
      #fortigate: "{{ item | regex_search('^(fortigate-1)_(.*)$', '\\1')}}"
      fortigate: "{{ item }}"
    loop: "{{ groups['all'] }}"
    when: item | regex_search("^fortigate-1_(.*)$") 

  - name: Add FortiGate node to the fortigate group
    add_host:
      name: "{{ fortigate }}"
      groups: fortigate

- name: Fortinet FortiGate roles
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortigate-config-network
    - fortigate-create-rules
    - fortigate-connect-fortianalyzer
    - fortigate-gather-facts
  tasks:
    - debug:
        var: fortigate
    - debug:
        var: hostvars[localhost]

