---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - utils_dynamic_hosts


- name: Fortinet FortiAnalyzer roles (workaround)
  hosts: fortianalyzer
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortianalyzer_fortigate_removal  # to avoid next errors
