---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
  tasks:
  - include_role: 
      name: utils_hosts_vmware
    when: infra == 'vmware'
  - include_role:
      name: utils_hosts_aws
    when: infra == 'aws'

- name: Fortinet FortiAnalyzer roles
  hosts: fortianalyzer
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortianalyzer_device_authorization
    - fortianalyzer_config_settings
    - fortianalyzer_gather_facts
