---

- name: Fortinet FortiGate roles
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortigate-gather-facts
    - fortigate-create-rules
    - fortigate-connect-fortianalyzer

