---

- name: Fortinet FortiManager roles
  hosts: fortimanager-1
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortimanager_config_settings
    #- fortimanager_add_fortigate   # not supported by FortiManager
    - fortimanager_add_fortianalyzer
    - fortimanager_gather_facts
  