---

- name: Fortinet FortiAnalyzer roles (workaround)
  hosts: fortianalyzer
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortianalyzer_fortigate_removal  # to avoid next errors
