---

# - name: VMware deployment roles
#   hosts: vmware
#   connection: local
#   gather_facts: no
#   vars_files: 
#     - main.yml
#     - "{{environment}}.yml"
#   roles:
#     - vmware_deploy_fortigate
#     - vmware_deploy_fortianalyzer
#     - vmware_deploy_fortimanager

- name: Fortinet FortiGate roles
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{environment}}.yml"
  roles:
    - fortigate-gather-facts
    - fortigate-create-rules
    - fortigate-connect-fortianalyzer

- name: Fortinet FortiAnalyzer roles
  hosts: fortianalyzer
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{environment}}.yml"
  roles:
    - fortianalyzer_device_authorization
    - fortianalyzer_config_settings
    - fortianalyzer_gather_facts
  
- name: Fortinet FortiManager roles
  hosts: fortimanager
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{environment}}.yml"
  roles:
    - fortimanager_gather_facts
    - fortimanager_add_device
    - fortimanager_config_settings
  