---
#config system global
#  set rest-api enable
#end
- name: Fortinet FortiGate role
  hosts: fortigate-1
  connection: httpapi
  gather_facts: no
  
  roles:
  #  - fortigate-gather-facts
  #  - fortigate-create-rules
    - fortigate-connect-fortianalyzer 
    
  