---

# - name: Fortinet FortiGate roles
#   hosts: fortigate-1
#   connection: httpapi
#   gather_facts: no
  
#   roles:
#     - fortigate-gather-facts
#     - fortigate-create-rules
#     - fortigate-connect-fortianalyzer 
  

- name: Fortinet FortiAnalyser roles
  hosts: fortianalyzer-1
  connection: httpapi
  gather_facts: no
  
  tasks:
    - name: Alert console
      fortinet.fortianalyzer.faz_cli_system_global:
        cli_system_global:
          language: english

  # roles:
  #   - fortianalyzer_device_authorization
  

  