---

# - name: Controller artifacts roles
#   hosts: controller-1
#   connection: local
#   gather_facts: no
#   vars_files: 
#     - main.yml
#     - "{{infra}}.yml"
#   roles:
#     - controller_create_artifacts

- name: VMware deployment roles
  hosts: vsphere-1
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - vmware_deploy_fortigate
    - vmware_deploy_fortianalyzer
    - vmware_deploy_fortimanager

- name: Fortinet FortiGate roles
  hosts: fortigate-1
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortigate-create-rules
    - fortigate-connect-fortianalyzer
    - fortigate-gather-facts

- name: Fortinet FortiAnalyzer roles
  hosts: fortianalyzer-1
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortianalyzer_config_settings
    - fortianalyzer_device_authorization
    - fortianalyzer_gather_facts

- name: Fortinet FortiAnalyzer roles (workaround)
  hosts: fortianalyzer-1
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortianalyzer_fortigate_removal  # to avoid next errors

- name: Fortinet FortiManager roles
  hosts: fortimanager-1
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - fortimanager_add_fortianalyzer
    - fortimanager_config_settings
    #- fortimanager_add_fortigate   # not supported by FortiManager
    - fortimanager_gather_facts

  