---

- name: Fortinet FortiGate roles
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars_files: 
    - ./vars/main.yml
    - ./vars/eve-ng.yml
    #- "./vars/{{inventory}}.yml"
  roles:
    - fortigate-gather-facts
    - fortigate-create-rules
    - fortigate-connect-fortianalyzer

# - name: Fortinet FortiAnalyser roles
#   hosts: fortianalyzer
#   connection: httpapi
#   gather_facts: no
#   roles:
#     - fortianalyzer_device_authorization
#     - fortianalyzer_config_settings
#     - fortianalyzer_gather_facts
  
# - name: Fortinet FortiManager roles
#   hosts: fortimanager
#   connection: httpapi
#   gather_facts: no
#   roles:
#     - fortimanager_gather_facts
#     - fortimanager_add_device
#     - fortimanager_config_settings
  
# - name: VMware deployment roles
#   hosts: vmware
#   connection: local
#   gather_facts: no
#   roles:
#     - vmware_deploy_fortigate
#     - vmware_deploy_fortianalyzer
#     - vmware_deploy_fortimanager