---
#config system global
#  set rest-api enable
#end
- name: Firewalls Fortinet
  hosts: fortigate-1
  connection: httpapi
  gather_facts: no
  
  roles:
    - fortigate-gather-facts
    - fortigate-create-rules
    
  