---

- name: VMware deployment roles
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - set_fact:
      fortigate: "{{ item | regex_search('^(fortigate-1)_(.*)$', '\\1'), first }}"
    loop: "{{ groups['all'] }}"
    when: item | regex_search("^fortigate-1_(.*)$")

  - debug:
      var: aaa
