---

- name: VMware deployment roles
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - set_fact:
      aaa: "aa" #"{{ item | regex_search('^fortinet-1(.*)$', '\\1'), first }}"
    loop: "{{ groups['all'] }}"
    when: item | regex_search("^(fortinet-1)(.*)$")

  - debug:
      var: aaa
