---

- name: VMware deployment roles
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - set_fact:
      fortigate: "{{ item | regex_search('^(fortigate-1)_(.*)$', '\\1')}}"
    loop: "{{ groups['all'] }}"
    when: item | regex_search("^fortigate-1_(.*)$") 

  - set_fact:
      fortianalyzer: "{{ item | regex_search('^(fortianalyzer-1)_(.*)$', '\\1') }}"
    loop: "{{ groups['all'] }}"
    when: item | regex_search("^fortianalyzer-1_(.*)$") 

  - set_fact:
      fortimanager: "{{ item | regex_search('^(fortimanager-1)_(.*)$', '\\1') }}"
    loop: "{{ groups['all'] }}"
    when: item | regex_search("^fortimanager-1_(.*)$") 

  - debug:
      var: fortigate
  - debug:
      var: fortianalyzer
  - debug:
      var: fortimanager
