---

- name: VMware deployment roles
  hosts: vsphere-1
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - vmware_deploy_fortigate
    - vmware_deploy_fortianalyzer
    - vmware_deploy_fortimanager
