---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
  tasks:
  - include_role: 
      name: utils_hosts_vmware
    when: infra == 'vmware'

- name: VMware undeployment roles
  hosts: vsphere
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  roles:
    - vmware_undeploy_all