---

# Create Credentials

- name: "Create Controller Tenant User '{{ controller_tenant_username }}'"
  awx.awx.user:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    username: "{{ controller_tenant_username }}"
    password: "{{ controller_tenant_password }}"
    organization: Default
    state: present

- name: "Add 'execute' permissions to tenant '{{ controller_tenant_username }}'"
  role:
    user: "{{ controller_tenant_username }}"
    role: execute
    job_templates:
      - "Fortinet: 2. deploy nodes"	
      - "Fortinet: 3. fortigate node"
      - "Fortinet: 4. fortianalyzer node"
      - "Fortinet: 5. fortimanager node"
    state: present

- name: "Add 'read' permissions to tenant '{{ controller_tenant_username }}'"
  role:
    user: "{{ controller_tenant_username }}"
    role: read
    credentials:
      - "Fortinet Credentials	Machine"	
      - "Fortinet vSphere Credentials"
    projects:
      - "Fortinet Project"
    inventories:
      - "Fortinet/VMWare Inventory dynamic"
    job_templates:
      - "Fortinet: 0. undeploy tenant/nodes"	
      - "Fortinet: 1. create tenant"
      - "Fortinet: workflow"
    state: present
