---

fortigate_vdom: "root"
#fortigate_token: 8dxz00ht3jstbs84Hfr0NHjr151Njf

fg_services:
  dns-tcp: service-dns-tcp
  dns-udp: service-dns-udp
  http: HTTP
  https: HTTPS

fg_fw_rules:
  - name: rule_C
    src:
      interface: "port2"
      addresses:
        - name: "inside_host_D"
          ipv4: "10.10.2.3"
    dest:
      interface: "port3"
      addresses:
        - name: "pub_host_A"
          type: host
          ipv4: "7.7.7.1"
        - name: "pub_host_B"
          type: host
          ipv4: "7.7.7.2"
    services:
      - http
      - https
    rule:
      action: "permit"
      logging_init: false
      logging_close: true
      ips_sensor: "default"
  - name: rule_D
    src:
      interface: "port3"
      addresses:
        - name: "pub_host_E"
          type: host
          ipv4: "7.7.7.3"
        - name: "pub_host_F"
          type: host
          ipv4: "7.7.7.4"
    dest:
      interface: "port2"
      addresses:
        - name: "inside_host_C"
          ipv4: "10.10.2.4"
    services:
      - http
      - https
    rule:
      action: "permit"
      logging_init: false
      logging_close: true
      ips_sensor: "default"