---

- name: Refresh inventory
  ansible.builtin.meta: refresh_inventory

- name: Get FortiGate node
  set_fact:
    fortigate: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: item | regex_search("^fortigate-1_(.*)$")

- name: Add FortiGate node to the fortigate group
  add_host:
    name: "{{ fortigate }}"
    groups: fortigate
  when: fortigate is defined

- name: Get FortiAnalyzer node
  set_fact:
    fortianalyzer: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: item | regex_search("^fortianalyzer-1_(.*)$") 

- name: Add FortiAnalyzer node to the fortianalyzer group
  add_host:
    name: "{{ fortianalyzer }}"
    groups: fortianalyzer
  when: fortianalyzer is defined

- name: Get FortiManager node
  set_fact:
    fortimanager: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: item | regex_search("^fortimanager-1_(.*)$") 

- name: Add FortiManager node to the fortimanager group
  add_host:
    name: "{{ fortimanager }}"
    groups: fortimanager
  when: fortimanager is defined

- name: Get vSphere node
  set_fact:
    vsphere: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: item | regex_search("^VMware vCenter Server_(.*)$") 

- name: Add vSphere node to the vsphere group
  add_host:
    name: "{{ vsphere }}"
    groups: vsphere
  when: vsphere is defined

- name: Get Controller node
  set_fact:
    controller: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: item | regex_search("^aap2-ctrl1.my-lab.local_(.*)$") 

- name: Add Controller node to the controller group
  add_host:
    name: "{{ controller }}"
    groups: controller
  when: controller is defined
