---

- name: Gather facts from Fortinet FortiGate
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ fortigate_vdom }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: "firewall_policy"
    #  - selector: "system_interface"
    #  - selector: "firewall_address"
  register: _fortinet_facts

- name: Debug FortiGate Facts
  debug:
    var: _fortinet_facts